# Generated by Django 5.2.1 on 2025-06-02 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Linha')),
            ],
            options={
                'verbose_name': 'Linha de Produção',
                'verbose_name_plural': 'Linhas de Produção',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Peça')),
                ('sap_code', models.CharField(max_length=50, unique=True, verbose_name='Código SAP')),
            ],
            options={
                'verbose_name': 'Peça',
                'verbose_name_plural': 'Peças',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TipoSystematic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Manutenção Preventiva', max_length=100, unique=True, verbose_name='Nome do Tipo')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do que este tipo de sistemática envolve.', null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Tipo de Sistemática',
                'verbose_name_plural': 'Tipos de Sistemáticas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Equipamento')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='core.line', verbose_name='Linha de Produção')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['line__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Systematic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Sistemática')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do Procedimento')),
                ('range_days', models.PositiveIntegerField(blank=True, default=0, help_text='Intervalo em dias para a próxima execução. 0 ou Nulo se não aplicável.', null=True, verbose_name='Frequência (dias)')),
                ('safety_instructions', models.TextField(blank=True, null=True, verbose_name='Instruções de Segurança')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systematics_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systematics', to='core.equipment', verbose_name='Equipamento')),
                ('tipo_systematic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='systematics', to='core.tiposystematic', verbose_name='Tipo de Sistemática')),
            ],
            options={
                'verbose_name': 'Sistemática',
                'verbose_name_plural': 'Sistemáticas',
                'ordering': ['equipment__line__name', 'equipment__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(help_text='Data em que a execução está/estava prevista', verbose_name='Data Agendada')),
                ('execution_start_date', models.DateTimeField(blank=True, help_text='Quando a execução efetivamente começou', null=True, verbose_name='Início da Execução')),
                ('execution_end_date', models.DateTimeField(blank=True, help_text='Quando a execução efetivamente terminou', null=True, verbose_name='Fim da Execução')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CONCLUIDA_ATRASO', 'Concluída com Atraso'), ('NAO_REALIZADA', 'Não Realizada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('observations', models.TextField(blank=True, help_text='Anotações, problemas encontrados, medições realizadas, etc.', null=True, verbose_name='Observações da Execução')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação do Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização do Registro')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systematics_executed', to=settings.AUTH_USER_MODEL, verbose_name='Executado por')),
                ('systematic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_records', to='core.systematic', verbose_name='Sistemática')),
            ],
            options={
                'verbose_name': 'Registro de Execução',
                'verbose_name_plural': 'Registros de Execução',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystematicPartRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Quantidade Necessária')),
                ('observation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_systematics_info', to='core.part', verbose_name='Peça')),
                ('systematic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_parts_info', to='core.systematic', verbose_name='Sistemática')),
            ],
            options={
                'verbose_name': 'Peça Necessária para Sistemática',
                'verbose_name_plural': 'Peças Necessárias para Sistemáticas',
                'ordering': ['systematic', 'part__name'],
                'unique_together': {('systematic', 'part')},
            },
        ),
    ]
