# Generated by Django 5.2.1 on 2025-06-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systematic_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='systematic',
            name='time_estimated_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Tempo estimado em minutos para execução', null=True, verbose_name='Tempo Estimado (min)'),
        ),
    ]
