# Generated by Django 5.2.1 on 2025-06-08 15:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systematic_time_estimated_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSystematic',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Nome da Sistemática')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do Procedimento')),
                ('range_days', models.PositiveIntegerField(blank=True, default=0, help_text='Intervalo em dias para a próxima execução. 0 ou Nulo se não aplicável.', null=True, verbose_name='Frequência (dias)')),
                ('time_estimated_minutes', models.PositiveIntegerField(blank=True, help_text='Tempo estimado em minutos para execução', null=True, verbose_name='Tempo Estimado (min)')),
                ('safety_instructions', models.TextField(blank=True, null=True, verbose_name='Instruções de Segurança')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sistemática Ativa?')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Atualização')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('equipment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.equipment', verbose_name='Equipamento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_systematic', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.tiposystematic', verbose_name='Tipo de Sistemática')),
            ],
            options={
                'verbose_name': 'historical Sistemática',
                'verbose_name_plural': 'historical Sistemáticas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
